//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practise
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public int ID { get; set; }
        public string unamee { get; set; }
        public string pass { get; set; }
        public Nullable<int> age { get; set; }
        public string gender { get; set; }
        public string Phonenumber { get; set; }
        public string City { get; set; }
    }
}
