//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practise
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_
    {
        public int Id { get; set; }
        public string A_Name { get; set; }
        public string A_Pass { get; set; }
        public Nullable<int> A_Age { get; set; }
        public string A_Gender { get; set; }
        public string A_PhoneNum { get; set; }
        public string A_City { get; set; }
    }
}
